FROM ubuntu:focal
RUN apt-get update
RUN apt-get install -y clang llvm libelf-dev libpcap-dev build-essential make 
RUN apt-get install -y linux-tools-common gcc-multilib linux-tools-generic
# COPY linux-tools-5.17.5-76051705_5.17.5-76051705.202204271406~1653440576~20.04~6277a18_amd64.deb /src/tools.deb
# COPY linux-tools-5.17.5-76051705-generic_5.17.5-76051705.202204271406~1653440576~20.04~6277a18_amd64.deb /src/tools-generic.deb
# RUN dpkg -i /src/tools.deb
# RUN dpkg -i /src/tools-generic.deb
